//生成命令：cd learn/x/grpc/; protoc --go_out=. --go-grpc_out=. --grpc-gateway_out=. helloworld.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: helloworld_gateway.proto

package helloworld

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequestGW struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Who     string `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
	YourAge int32  `protobuf:"varint,2,opt,name=your_age,json=yourAge,proto3" json:"your_age,omitempty"`
}

func (x *HelloRequestGW) Reset() {
	*x = HelloRequestGW{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestGW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestGW) ProtoMessage() {}

func (x *HelloRequestGW) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestGW.ProtoReflect.Descriptor instead.
func (*HelloRequestGW) Descriptor() ([]byte, []int) {
	return file_helloworld_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequestGW) GetWho() string {
	if x != nil {
		return x.Who
	}
	return ""
}

func (x *HelloRequestGW) GetYourAge() int32 {
	if x != nil {
		return x.YourAge
	}
	return 0
}

type HelloReplyGW struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *HelloReplyGW) Reset() {
	*x = HelloReplyGW{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReplyGW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReplyGW) ProtoMessage() {}

func (x *HelloReplyGW) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReplyGW.ProtoReflect.Descriptor instead.
func (*HelloReplyGW) Descriptor() ([]byte, []int) {
	return file_helloworld_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReplyGW) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloReplyGW) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type HelloGetRequestGW struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HelloGetRequestGW) Reset() {
	*x = HelloGetRequestGW{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloGetRequestGW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloGetRequestGW) ProtoMessage() {}

func (x *HelloGetRequestGW) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloGetRequestGW.ProtoReflect.Descriptor instead.
func (*HelloGetRequestGW) Descriptor() ([]byte, []int) {
	return file_helloworld_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *HelloGetRequestGW) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HelloGetReplyGW struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HelloGetReplyGW) Reset() {
	*x = HelloGetReplyGW{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloGetReplyGW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloGetReplyGW) ProtoMessage() {}

func (x *HelloGetReplyGW) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloGetReplyGW.ProtoReflect.Descriptor instead.
func (*HelloGetReplyGW) Descriptor() ([]byte, []int) {
	return file_helloworld_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HelloGetReplyGW) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_helloworld_gateway_proto protoreflect.FileDescriptor

var file_helloworld_gateway_proto_rawDesc = []byte{
	0x0a, 0x18, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x0e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x47, 0x57, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x77, 0x68, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x79, 0x6f, 0x75, 0x72,
	0x5f, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x79, 0x6f, 0x75, 0x72,
	0x41, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x47, 0x57, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x57, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23,
	0x0a, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47,
	0x57, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x32, 0xed, 0x01, 0x0a, 0x09, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x47,
	0x57, 0x12, 0x60, 0x0a, 0x0e, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x57, 0x4a,
	0x53, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x57, 0x1a,
	0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x57, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x7e, 0x0a, 0x0d, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47,
	0x57, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x47, 0x57, 0x1a, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x57,
	0x22, 0x31, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2b, 0x5a, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x65, 0x74, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x47, 0x65, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworld_gateway_proto_rawDescOnce sync.Once
	file_helloworld_gateway_proto_rawDescData = file_helloworld_gateway_proto_rawDesc
)

func file_helloworld_gateway_proto_rawDescGZIP() []byte {
	file_helloworld_gateway_proto_rawDescOnce.Do(func() {
		file_helloworld_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld_gateway_proto_rawDescData)
	})
	return file_helloworld_gateway_proto_rawDescData
}

var file_helloworld_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_gateway_proto_goTypes = []interface{}{
	(*HelloRequestGW)(nil),    // 0: helloworld.HelloRequestGW
	(*HelloReplyGW)(nil),      // 1: helloworld.HelloReplyGW
	(*HelloGetRequestGW)(nil), // 2: helloworld.HelloGetRequestGW
	(*HelloGetReplyGW)(nil),   // 3: helloworld.HelloGetReplyGW
}
var file_helloworld_gateway_proto_depIdxs = []int32{
	0, // 0: helloworld.GreeterGW.SayHelloGWJSon:input_type -> helloworld.HelloRequestGW
	2, // 1: helloworld.GreeterGW.SayHelloGWGet:input_type -> helloworld.HelloGetRequestGW
	1, // 2: helloworld.GreeterGW.SayHelloGWJSon:output_type -> helloworld.HelloReplyGW
	3, // 3: helloworld.GreeterGW.SayHelloGWGet:output_type -> helloworld.HelloGetReplyGW
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_gateway_proto_init() }
func file_helloworld_gateway_proto_init() {
	if File_helloworld_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworld_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestGW); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReplyGW); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloGetRequestGW); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloGetReplyGW); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworld_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_gateway_proto_goTypes,
		DependencyIndexes: file_helloworld_gateway_proto_depIdxs,
		MessageInfos:      file_helloworld_gateway_proto_msgTypes,
	}.Build()
	File_helloworld_gateway_proto = out.File
	file_helloworld_gateway_proto_rawDesc = nil
	file_helloworld_gateway_proto_goTypes = nil
	file_helloworld_gateway_proto_depIdxs = nil
}
